version: '3.4'

services:
  nginx:
    container_name: "rusatom-test-nginx"
    image: nginx:alpine
    volumes:
      - ./docker/nginx:/etc/nginx/conf.d:ro
      - ./docker/log/nginx:/var/log/nginx:rw
      - ./public:/var/www/app/public:delegated
    ports:
      - "80:80"

  php:
    container_name: 'rusatom-test-php'
    build:
      context: docker/php
      dockerfile: Dockerfile
    user: "1000:1000"
    volumes:
      - .:/var/www/app:delegated
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
    working_dir: /var/www/app
    ports:
      - "8707:8707"

  postgresql:
    container_name: "rusatom-test-postgres"
    restart: on-failure
    image: postgres
    build:
      context: docker/postgres
      dockerfile: Dockerfile
    ports:
      - "5432:5432"
    environment:
      - DEBUG=false
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=rusatom_db
    volumes:
      - postgresql-data:/var/lib/postgresql

  elasticsearch:
    container_name: "rusatom-test-elastic"
    image: docker.elastic.co/elasticsearch/elasticsearch:7.14.1
    volumes:
      - esdata1:/usr/share/elasticsearch/data
      - ./docker/elastic/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "9100:9100"
      - "9200:9200"
    ulimits:
      memlock:
        soft: -1
        hard: -1

volumes:
  postgresql-data:
  esdata1:
    driver: local
